- name: NGINX | Install and configure NGINX, filebeat, logstash
  hosts: WEB
  become: true
  vars_files: 
        - vars/vars.yml
  tasks:
    - name: NGINX | Install EPEL Repo package from standart repo
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: NGINX | Install NGINX package from EPEL 
      yum:
        name: nginx
        state: latest
      notify:
        - restart nginx
      tags:
        - nginx-package
        - packages

    - name: Add Elasticsearch GPG key.
      rpm_key:
        key: https://packages.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Filebeat repository.
      template:
        src: beats.repo.j2
        dest: /etc/yum.repos.d/beats.repo
        mode: 0644
      
    - name: Install Filebeat
      yum:
        name: filebeat
        state: latest
      notify:
        - restart filebeat

    - name: filebeat_config
      template:
         src: "templates/filebeat.yml.j2"
         dest: "/etc/filebeat/filebeat.yml"
         owner: root
         group: root
         mode: 0644
      notify: restart filebeat
      tags: filebeat_config

    - name: enable service filebeat
      systemd:
       name: filebeat
       enabled: yes

    - name: Install Logstash
      yum:
        name: logstash
        state: latest
      notify:
        - restart logstash

    - name: enable service Logstash
      systemd:
       name: logstash
       enabled: yes

    - name: config Logstash
      template:
         src: "templates/10-pipeline.conf.j2"
         dest: "/etc/logstash/conf.d/10-pipeline.conf"
         owner: root
         group: root
         mode: 0644
      notify: restart logstash

    - name: Install Auditbeat
      yum:
        name: auditbeat
        state: latest
      notify:
        - restart auditbeat

    - name: enable service auditbeat
      systemd:
       name: auditbeat
       enabled: yes

    - name: config auditbeat
      template:
         src: "templates/auditbeat.yml.j2"
         dest: "/etc/auditbeat/auditbeat.yml"
         owner: root
         group: root
         mode: 0644
      notify: restart auditbeat

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
    
    - name: restart filebeat
      systemd:
        name: filebeat
        state: restarted
        enabled: yes
    
    - name: restart logstash
      systemd:
        name: logstash
        state: restarted
        enabled: yes
    
    - name: restart auditbeat
      systemd:
        name: auditbeat
        state: restarted
        enabled: yes

- name: Elasticsearch and Kibana Install
  hosts: LOG
  become: true
  vars_files: 
        - vars/vars.yml
  tasks:
    - name: Add Elasticsearch GPG key.
      rpm_key:
        key: https://packages.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elastic repository.
      template:
        src: beats.repo.j2
        dest: /etc/yum.repos.d/elastic.repo
        mode: 0644

    - name: Install Elasticsearch
      yum:
        name: elasticsearch
        state: latest
      notify:
        - restart elasticsearch

    - name: enable service elasticsearch
      systemd:
       name: elasticsearch
       enabled: yes

    - name: elasticsearch config
      template:
         src: "templates/elasticsearch.yml.j2"
         dest: "/etc/elasticsearch/elasticsearch.yml"
         owner: root
         group: root
         mode: 0644
      notify: restart elasticsearch
      tags: elasticsearch_config

    - name: Install Kibana
      yum:
        name: kibana
        state: latest

    - name: enable service Kibana
      systemd:
       name: kibana
       enabled: yes

    - name: kibana config
      template:
         src: "templates/kibana.yml.j2"
         dest: "/etc/kibana/kibana.yml"
         owner: root
         group: root
         mode: 0644
      notify: restart kibana
      tags: kibana_config
       
  handlers:
    - name: restart elasticsearch
      systemd:
        name: elasticsearch
        state: restarted
        enabled: yes

    - name: restart kibana
      systemd:
        name: kibana
        state: restarted
        enabled: yes
    
  