servers:
  hosts:
    WEB:
      ansible_host: 127.0.0.1
      ansible_port: 2222
      ansible_private_key_file: /root/OTUS/Kazay/logs/.vagrant/machines/server/virtualbox/private_key
    LOG:
      ansible_host: 127.0.0.1
      ansible_port: 2200
      ansible_private_key_file: /root/OTUS/Kazay/logs/.vagrant/machines/client/virtualbox/private_key