- name: NGINX | Install and configure NGINX and Filebeat
  hosts: WEB
  become: true
  vars_files: 
        - vars/vars.yml
  tasks:
    - name: NGINX | Install EPEL Repo package from standart repo
      yum:
        name: epel-release
        state: present
      tags:
        - epel-package
        - packages

    - name: NGINX | Install NGINX package from EPEL 
      yum:
        name: nginx
        state: latest
      notify:
        - restart nginx
      tags:
        - nginx-package
        - packages

    - name: Add Elasticsearch GPG key.
      rpm_key:
        key: https://packages.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Filebeat repository.
      template:
        src: beats.repo.j2
        dest: /etc/yum.repos.d/beats.repo
        mode: 0644
      
    - name: Install Filebeat
      yum:
        name: filebeat
        state: latest
      notify:
        - restart filebeat

    - name: filebeat_config
      template:
         src: "templates/filebeat.yml.j2"
         dest: "/etc/filebeat/filebeat.yml"
         owner: root
         group: root
         mode: 0644
      notify: restart filebeat
      tags: filebeat_config

    - name: enable service filebeat
      systemd:
       name: filebeat
       enabled: yes

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
        enabled: yes
    
    - name: reload nginx
      systemd:
        name: nginx
        state: reloaded
    
    - name: restart filebeat
      systemd:
        name: filebeat
        state: restarted
        enabled: yes


- name: Logstash, Elasticsearch and Kibana Install
  hosts: LOG
  become: true
  vars_files: 
        - vars/vars.yml
  tasks:
    - name: Add Elasticsearch GPG key.
      rpm_key:
        key: https://packages.elastic.co/GPG-KEY-elasticsearch
        state: present

    - name: Add Elastic repository.
      template:
        src: beats.repo.j2
        dest: /etc/yum.repos.d/elastic.repo
        mode: 0644

    - name: Install Elasticsearch
      yum:
        name: elasticsearch
        state: latest
      notify:
        - restart elasticsearch

    - name: enable service elasticsearch
      systemd:
       name: elasticsearch
       enabled: yes
      
    - name: Install Logstash
      yum:
        name: logstash
        state: latest
      notify:
        - restart logstash

    - name: enable service Logstash
      systemd:
       name: logstash
       enabled: yes

    - name: config Logstash
      template:
         src: "templates/10-pipline.conf.j2"
         dest: "/etc/logstash/conf.d/10-pipeline.conf"
         owner: root
         group: root
         mode: 0644
      notify: restart logstash
         
  handlers:
    - name: restart logstash
      systemd:
        name: logstash
        state: restarted
        enabled: yes

    - name: restart elasticsearch
      systemd:
        name: elasticsearch
        state: restarted
        enabled: yes
    
  